Excerce 1 : Working with Scalars and Vectors

In [2]:
import numpy as np

scaler = 9
print(scaler)

vector = np.array([3,6,8,45,19])
print(vector)

scaled_vector = scaler * vector
print("Scaled vector =",scaled_vector)

print("Sum of scaler and vector",scaler + vector)

9
[ 3  6  8 45 19]
Scaled vector = [ 27  54  72 405 171]
Sum of scaler and vector [12 15 17 54 28]


Matrix creation and simple operation

In [9]:
matrix1 = np.array([[1,2], [4,5]])
matrix2 = np.array([[2,3], [6,7]])

print("sum",matrix1 + matrix2)
print("diff",matrix1 - matrix2)

multi = np.dot(matrix1, matrix2)
print("multi",multi)

sum [[ 3  5]
 [10 12]]
diff [[-1 -1]
 [-2 -2]]
multi [[14 17]
 [38 47]]


In [12]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

mat1_x_mat2 = np.array([
    [mat1[0,0]*mat2[0,0] + mat1[0,1]*mat2[1,0],
     mat1[0,0]*mat2[0,1] + mat1[0,1]*mat2[1,1]],

    [mat1[1,0]*mat2[0,0] + mat1[1,1]*mat2[1,0],
     mat1[1,0]*mat2[0,1] + mat1[1,1]*mat2[1,1]]
])

print(mat1_x_mat2)

check = np.dot(mat1,mat2)
print(check)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
